# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
# name: Henry Torres
title: "El software de Henry Torres "
subtitle: "Software para la atmosfera"
logo: "/assets/images/icons8-case-study-48.png"

email: henrytorrespo@yahoo.com
description: Ingeniero con estudios de maestria en Ingenieria Ambiental y magister en Ciencias de la Computacion.
twitter_username: #username
github_username: tthen
minimal_mistakes_skin: "air" # "air", "aqua", "contrast", "dark", "dirt", "neon", "mint", "plum", "sunrise"
search: true
repository: "tthen/tthen.github.io" # GitHub username/repo-name e.g. "mmistakes/minimal-mistakes"

# Build settings
markdown: kramdown
remote_theme: mmistakes/minimal-mistakes@4.24.0
# Outputting
permalink: /:categories/:title/
paginate: 5 # amount of posts to show
paginate_path: /page:num/
timezone: # https://en.wikipedia.org/wiki/List_of_tz_database_time_zones

include:
  - _pages

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

# Plugins (previously gems:)
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-include-cache
  - jekyll-archives
  - jekyll-seo-tag

# mimic GitHub Pages with --safe
whitelist:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jekyll-include-cache
  - jekyll-archives
  - jekyll-seo-tag

analytics:
  provider: "google-gtag"
  google:
    tracking_id: #"G-1T8HPSB27P"
    anonymize_ip: false # default

author:
  name      : "Adam Gladstone"
  avatar    : "/assets/images/bio-photo.png"
  bio       : "Disfruto escribir software para agilizar los procesos de modelado y analisis de datos con Python y R."
  location  : "Bogota, D.C., Colombia"
  links:
    - label: "Website"
      icon: "fas fa-fw fa-link"
      url: "https://tthen.github.io"
    - label: "Email"
      icon: "fas fa-fw fa-envelope-square"
      url: "mailto:henrytorrespo@yahoo.com"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/"
    - label: "LinkedIn"
      icon: "fab fa-fw fa-linkedin"
      url: "https://www.linkedin.com/in/htorrespo/"
    - label: "R-bloggers"
      icon: "fab fa-fw fa-r-project"
      url: "http://www.R-bloggers.com"
    - label: "Python-bloggers"
      icon: "fab fa-fw fa-python"
      url: "https://python-bloggers.com"


footer:
  links:
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/"
    - label: "LinkedIn"
      icon: "fab fa-fw fa-linkedin"
      url: "https://www.linkedin.com/in/htorrespo/"
    - label: "R-bloggers"
      icon: "fab fa-fw fa-r-project"
      url: "http://www.R-bloggers.com"
    - label: "Python-bloggers"
      icon: "fab fa-fw fa-python"
      url: "https://python-bloggers.com"

defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: true
      share: false
      related: true
  # _pages
  - scope:
      path: "_pages"
      type: pages
    values:
      layout: single
      author_profile: true

comments:
  provider: "utterances"
  utterances:
    theme: "github-light" # "github-dark"
    issue_term: "pathname"
    label: "comment" # Optional - must be existing label.


category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/

# Exclude these files from your production _site
exclude:
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - CNAME
